# Site settings
title: Test Foo
email:
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

theme: jekyll-swiss
theme_color: red

# Build settings
markdown: kramdown
