# Site settings
title: Daniel Hahn
email:
description: >
  This is the hub for my stuff (and federated elsewhere). Everything else is
  just a repost.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.danielhahn.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

social_link: github
github_username: averell23

theme: jekyll-swiss
theme_color: red

# Build settings
markdown: kramdown

author:
  name: "Daniel Hahn"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
